kind: pipeline
type: docker
name: glue-health-check

trigger:
  event:
    - pull_request

steps:
  - name: glue-health-check
    image: hashicorp/terraform:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - ./scripts/glue_health_check.sh
